# Generated by Django 6.0.1 on 2026-01-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('Soul', 'Душа'), ('Personal', 'Личное'), ('Work', 'Работа')], default='Personal', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='date',
            name='habit_date',
            field=models.DateField(verbose_name='Дата привычки'),
        ),
        migrations.AlterField(
            model_name='date',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Сделано'),
        ),
        migrations.AlterField(
            model_name='date',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='date',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='userall',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг'),
        ),
    ]
