# Generated by Django 6.0 on 2025-12-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='habit_date',
            field=models.DateTimeField(max_length=100, verbose_name='Дата привычки'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('user', models.ManyToManyField(related_name='achievement', to='api.userall')),
            ],
            options={
                'verbose_name': 'Ачивка',
                'verbose_name_plural': 'Ачивки',
            },
        ),
    ]
