# Generated by Django 6.0.1 on 2026-01-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_date_habit_date_achievement'),
        ('api', '0002_habit_category_alter_date_habit_date_and_more'),
    ]

    operations = [
    ]
