# Generated by Django 6.0.1 on 2026-01-20 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20260120_1711'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userall',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django'),
        ),
        migrations.AlterField(
            model_name='date',
            name='habit_date',
            field=models.DateField(max_length=100, verbose_name='Дата привычки'),
        ),
        migrations.AlterField(
            model_name='userall',
            name='age',
            field=models.CharField(blank=True, max_length=100, verbose_name='Возраст'),
        ),
    ]
