# Generated by Django 5.2.9 on 2026-01-22 15:00

import django.db.models.deletion
from django.db import migrations, models


from django.utils.text import slugify

def migrate_categories_to_objects(apps, schema_editor):
    Habit = apps.get_model('api', 'Habit')
    Category = apps.get_model('api', 'Category')
    
    cat_map = {
        'Soul': 'Душа',
        'Personal': 'Личное',
        'Work': 'Работа'
    }
    
    for habit in Habit.objects.all():
        cat_name = cat_map.get(habit.category_old, habit.category_old)
        if not cat_name or not habit.user:
            continue
            
        slug = slugify(cat_name)
        # Handle unique slug per user in migration
        final_slug = slug
        num = 1
        while Category.objects.filter(user=habit.user, slug=final_slug).exists():
            final_slug = f"{slug}-{num}"
            num += 1

        category, _ = Category.objects.get_or_create(
            user=habit.user,
            name=cat_name,
            defaults={'slug': final_slug}
        )
        habit.category_id = category.id
        habit.save()

def copy_category_to_old(apps, schema_editor):
    Habit = apps.get_model('api', 'Habit')
    for habit in Habit.objects.all():
        habit.category_old = habit.category
        habit.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userall_auth_user_alter_date_habit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category_old',
            field=models.CharField(choices=[('Soul', 'Душа'), ('Personal', 'Личное'), ('Work', 'Работа')], default='Personal', max_length=20, verbose_name='Старая категория'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Слаг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.userall')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'unique_together': {('user', 'name'), ('user', 'slug')},
            },
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(copy_category_to_old),
        migrations.RunSQL("UPDATE api_habit SET category = NULL;"),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='api.category', verbose_name='Категория'),
        ),
        migrations.RunPython(migrate_categories_to_objects),
    ]
