# Generated by Django 6.0.1 on 2026-01-27 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_habit_category_old_category_alter_habit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название'),
        ),
    ]
