# Generated by Django 6.0.1 on 2026-01-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Количество выполненных действий (например, 30 отжиманий)', null=True, verbose_name='Количество'),
        ),
    ]
