# Generated by Django 6.0.1 on 2026-02-19 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_date_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Количество выполненных действий (например, 30 отжиманий)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Количество'),
        ),
    ]
