# Generated by Django 6.0.1 on 2026-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_date_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='date',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='habit_photos/', verbose_name='Фото'),
        ),
    ]
