# Generated by Django 5.2.9 on 2026-02-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_habit_order_archive'),
        ('api', '0009_date_comment_date_photo'),
    ]

    operations = [
    ]
