# Generated by Django 5.2.9 on 2026-03-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20260225_1321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='date',
            unique_together={('user', 'habit', 'habit_date')},
        ),
    ]
