# Generated by Django 5.2.9 on 2026-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_date_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='is_replenished',
            field=models.BooleanField(default=False, verbose_name='Восполнено'),
        ),
    ]
