# Generated by Django 5.2.9 on 2026-03-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_date_is_replenished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='is_replenished',
            new_name='is_restored',
        ),
    ]
