# Generated by Django 5.2.9 on 2026-03-17 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_is_replenished_date_is_restored'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
