# Generated by Django 5.2.9 on 2026-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_category_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='userall',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
