# Generated by Django 5.2.9 on 2026-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_userall_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userall',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото профиля'),
        ),
    ]
