# Generated by Django 6.0.2 on 2026-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userall_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateField(blank=True, help_text='Дата создания привычки (можно изменить)', null=True, verbose_name='Дата начала'),
        ),
    ]
