# Generated by Django 5.2.9 on 2026-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userall_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='target_type',
            field=models.CharField(choices=[('at_least', 'Не менее (зеленая)'), ('less_or_equal', 'Не более (светло-зеленая)')], default='at_least', help_text='Тип цели привычки: не менее (зеленая) или не более (светло-зеленая)', max_length=20, verbose_name='Тип цели'),
        ),
    ]
