# Generated by Django 5.2.9 on 2026-04-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_target_type_to_habit'),
        ('api', '0020_remove_habit_created_at_habit_start_date'),
    ]

    operations = [
    ]
