# Generated by Django 5.2.9 on 2026-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20260430_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='target_type',
            field=models.CharField(choices=[('at_least', 'Не менее (светло-зеленая)'), ('less_or_equal', 'Не более (зеленая)')], default='at_least', help_text='Тип цели привычки: не менее (светло-зеленая) или не более (зеленая)', max_length=20, verbose_name='Тип цели'),
        ),
    ]
