# Generated by Django 6.0.2 on 2026-05-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_target_type_to_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='api.userall')),
            ],
            options={
                'verbose_name': 'Подписка на пуш',
                'verbose_name_plural': 'Подписки на пуш',
            },
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('text', models.CharField(default='Не забудьте отметить привычки!', max_length=255, verbose_name='Текст напоминания')),
                ('times', models.JSONField(default=list, verbose_name='Время напоминаний')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='api.userall')),
            ],
            options={
                'verbose_name': 'Настройки напоминаний',
                'verbose_name_plural': 'Настройки напоминаний',
            },
        ),
    ]
