# Generated by Django 6.0.2 on 2026-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_pushsubscription_remindersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completion_target',
            field=models.IntegerField(blank=True, help_text='Целевое количество дней выполнения в месяц', null=True, verbose_name='Цель выполнения'),
        ),
        migrations.AddField(
            model_name='habit',
            name='quantity_target',
            field=models.IntegerField(blank=True, help_text='Целевое количество действий (например, страниц) в месяц', null=True, verbose_name='Цель количества'),
        ),
        migrations.AddField(
            model_name='habit',
            name='use_target',
            field=models.BooleanField(default=False, verbose_name='Использовать цель'),
        ),
    ]
