# Generated by Django 6.0.2 on 2026-06-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_habit_completion_target_habit_quantity_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindersettings',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=64, verbose_name='Часовой пояс'),
        ),
    ]
